import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import { ClerkProvider } from "@clerk/nextjs";
import { UserButton } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`proseOFF dark:prose-invertOFF ${inter.className}`}>
          <header>
            <nav>
              <Link href="/">Home</Link>
              <Link href="/blog">Blog</Link>
              <UserButton afterSignOutUrl="/" />
            </nav>
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
